Repository PalisadoesFoundation/talawa, pull requests merged in 2021-04, with the labels that each got.

#548 resolved article description clarity issue
  lib/views/pages/newsfeed/newsArticle.dart
Labels: bug, good first issue

#564 [Fix] Membership requests are not being displayed on the Accept Membership Requests page
  lib/views/pages/organization/accept_requests_page.dart
  test/widget_tests/accept_requests_page_test.dart
Labels: bug

#560 feat: remove duplicate images declared in pubspec.yaml
  pubspec.yaml
Labels: bug

#573 [FIX] organization name not showing
  lib/views/pages/organization/profile_page.dart
Labels: bug, good first issue

#574 [BugFix] Update comment count on Newsfeed page after adding comment .
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/newsfeed/newsfeed.dart
Labels: bug, help wanted

#225 Create Organization Page Form Filling UX enhancement
  lib/views/pages/organization/create_organization.dart
Labels: enhancement, hold

#308 decorate chat textfield
  lib/views/pages/chat/chat.dart
Labels: enhancement, hold

#613 Encryption
  android/app/build.gradle
  lib/services/preferences.dart
  pubspec.yaml
Labels: enhancement, good first issue, help wanted

#619 Profile page now updating on joining organization and exception thrown on toast fixed.
  lib/views/pages/organization/join_organization.dart
Labels: bug, good first issue

#621 [Fixed Bug] Validation added in addtask
  lib/views/pages/events/addTaskDialog.dart
  test/widget_tests/addTaskDialog_test.dart
Labels: bug

#639 [Fix] Time of comment updated on UI for every single second
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/organization/create_organization.dart
Labels: bug, good first issue

#640 [Bug]Screen Stacking fix using pop
  lib/views/pages/organization/switch_org_page.dart
  lib/views/pages/organization/update_profile_page.dart
Labels: enhancement, good first issue

#641 [Bug] Comment input bug removal
  lib/main.dart
  lib/model/comment.dart
  lib/services/comment.dart
  lib/views/pages/newsfeed/newsArticle.dart
  test/unit_tests/commentModel_test.dart
  test/widget_tests/newsArticle_test.dart
Labels: bug

#596 changed the location of the Issue template and pr template
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PR_TEMPLATE/pr-template.md
  PR-guidelines.md
  issue-guidelines.md
Labels: documentation, good first issue

#558 Fixing Edit Event functionality
  lib/services/Queries.dart
  lib/views/pages/events/editEventDialog.dart
  lib/views/pages/events/events.dart
  lib/views/widgets/showProgress.dart
  pubspec.yaml
Labels: bug

#633 Fixed create Organization direct hit API validation error with tricky data
  lib/utils/validator.dart
  lib/views/pages/organization/create_organization.dart
Labels: bug, good first issue

#653 Fixed Spinner Issue and Resized Spinner Size
  lib/views/pages/organization/join_organization.dart
Labels: bug, good first issue

#658 resolved exception
  lib/utils/globals.dart
Labels: bug, good first issue

#539 Changed the graphQL interpolation method of sending data from the app
  lib/services/Queries.dart
  lib/views/pages/events/addEventPage.dart
  lib/views/pages/events/events.dart
  lib/views/pages/newsfeed/addPost.dart
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/newsfeed/newsfeed.dart
Labels: enhancement, hold

#585 [Fix] : Mapping of Registered Events and Tasks in the Member Pages
  lib/services/Queries.dart
  lib/views/pages/events/registrantList.dart
  lib/views/pages/events/taskList.dart
  lib/views/pages/login_signup/set_url_page.dart
  lib/views/pages/members/RegEventstab.dart
  lib/views/pages/members/members.dart
  lib/views/pages/members/userTaskstab.dart
  test/widget_tests/userTaskTab_test.dart
Labels: enhancement, help wanted, hold

#656 fix: joined & created organizations showing in ListView
  lib/views/pages/organization/join_organization.dart
Labels: bug, good first issue

#671 Fixes delayed appearance of new events in the events list [Fixes #660]
  lib/views/pages/events/addEventPage.dart
  lib/views/pages/events/events.dart
Labels: bug, good first issue

#676 Fixed overflow problem of addpost
  lib/views/pages/home_page.dart
  lib/views/pages/newsfeed/addPost.dart
Labels: bug, good first issue

#672 News feed get posts bug fix
  lib/views/pages/newsfeed/newsfeed.dart
Labels: bug

#497 Feat:Add logs
  android/app/build.gradle
  lib/main.dart
  lib/utils/api_functions.dart
  lib/utils/loghelper.dart
  lib/views/pages/login_signup/set_url_page.dart
  pubspec.yaml
Labels: enhancement, help wanted, hold

#518 Fix: Proper State Management (Removal of Pull to Refresh Feature) #334
  lib/controllers/post_controller.dart
  lib/main.dart
  lib/views/pages/home_page.dart
  lib/views/pages/newsfeed/news_article.dart
  lib/views/pages/newsfeed/newsfeed.dart
  lib/views/pages/organization/join_organization.dart
  pubspec.yaml
  test/update_profile_test.dart
  test/widget_tests/add_post_test.dart
  test/widget_tests/home_page_test.dart
  test/widget_tests/news_article_test.dart
Labels: enhancement, hold

#271 [Enhancement] Dialog enhancement for iOS
  lib/views/pages/organization/join_organization.dart
  lib/views/pages/organization/profile_page.dart
Labels: good first issue

#740 Adding countline.py to resolve Issue 725
  .github/workflows/countline.py
  .github/workflows/countline.sh
  .github/workflows/pull-request.yml
Labels: good first issue, help wanted
