Repository PalisadoesFoundation/talawa, pull requests merged in 2021-05, with the labels that each got.

#423 Changed built-in widget constructors to corresponding const constructors wherever necessary
  lib/model/token.dart
  lib/views/pages/chat/chat.dart
  lib/views/pages/chat/groups.dart
  lib/views/pages/events/add_event_page.dart
  lib/views/pages/events/edit_event_dialog.dart
  lib/views/pages/events/event_detail_page.dart
  lib/views/pages/events/events.dart
  lib/views/pages/home_page.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/login_signup/register_page.dart
  lib/views/pages/login_signup/set_url_page.dart
  lib/views/pages/members/member_details.dart
  lib/views/pages/members/members.dart
  lib/views/pages/organization/create_organization.dart
  lib/views/pages/organization/join_organization.dart
  lib/views/pages/organization/organization_settings.dart
  lib/views/pages/organization/profile_page.dart
  lib/views/pages/organization/update_organization.dart
  pubspec.yaml
  test/widget_tests/const_constructors_test.dart
Labels: enhancement, good first issue

#754 [Fix] Modification of Loading widget to make it a universal loading widget
  lib/main.dart
  lib/services/groups_provider.dart
  lib/services/post_provider.dart
  lib/utils/validator.dart
  lib/view_models/page_view_model/events_page_view_model.dart
  lib/views/pages/chat/groups.dart
  lib/views/pages/events/events.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/members/members.dart
  lib/views/pages/members/reg_eventstab.dart
  lib/views/pages/members/user_taskstab.dart
  lib/views/pages/newsfeed/newsfeed.dart
  lib/views/pages/organization/join_organization.dart
  lib/views/pages/organization/profile_page.dart
  lib/views/widgets/custom_appbar.dart
  lib/views/widgets/loading.dart
  test/widget_tests/groups_page_test.dart
  test/widget_tests/newsfeed_test.dart
  test/widget_tests/user_task_tab_test.dart
Labels: code refactor, enhancement

#790 Implemented MVVM on profile_page.dart
  lib/locator.dart
  lib/main.dart
  lib/view_models/page_view_model/profile_page_viewModel.dart
  lib/views/pages/organization/profile_page.dart
  test/widget_tests/profile_page_test.dart
Labels: code refactor, enhancement

#791 Implemented MVVM on news_article.dart
  lib/locator.dart
  lib/view_models/newwfeed_view_model/new_article_page_view_model.dart
  lib/views/pages/newsfeed/news_article.dart
  test/widget_tests/news_article_test.dart
Labels: code refactor, enhancement

#788 Implemented MVVM on create_organization_view.dart
  lib/locator.dart
  lib/main.dart
  lib/view_models/page_view_model/create_organization_page_viewModel.dart
  lib/views/pages/organization/Create Organization/create_organization_UI_Helper.dart
  lib/views/pages/organization/Create Organization/create_organization_view.dart
  lib/views/pages/organization/create_organization.dart
  lib/views/pages/organization/join_organization.dart
Labels: code refactor, enhancement

#752 Formatted the code by adding trailing commas
  analysis_options.yaml
  lib/controllers/auth_controller.dart
  lib/controllers/post_controller.dart
  lib/enums/connectivity_status.dart
  lib/enums/viewstate.dart
  lib/model/switch_org.dart
  lib/model/token.dart
  lib/services/api_.dart
  lib/services/comment.dart
  lib/services/preferences.dart
  lib/services/queries_.dart
  lib/utils/api_functions.dart
  lib/utils/custom_toast.dart
  lib/utils/exception_classifier.dart
  lib/utils/gql_client.dart
  lib/utils/graph_api.dart
  lib/utils/loghelper.dart
  lib/utils/timer.dart
  lib/utils/ui_scaling.dart
  lib/utils/uidata.dart
  lib/utils/user_info.dart
  lib/utils/validator.dart
  lib/view_models/swtich_org_vm.dart
  lib/view_models/vm_login.dart
  lib/view_models/vm_register.dart
  lib/views/base_view.dart
  lib/views/pages/chat/chat.dart
  lib/views/pages/chat/groups.dart
  lib/views/pages/events/add_event_page.dart
  lib/views/pages/events/add_task_dialog.dart
  lib/views/pages/events/edit_event_dialog.dart
  lib/views/pages/events/event_detail_page.dart
  lib/views/pages/events/events.dart
  lib/views/pages/events/registrant_list.dart
  lib/views/pages/events/task_list.dart
  lib/views/pages/home_page.dart
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/login_signup/login_page.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/login_signup/register_page.dart
  lib/views/pages/login_signup/set_url_page.dart
  lib/views/pages/members/member_details.dart
  lib/views/pages/members/reg_eventstab.dart
  lib/views/pages/members/user_taskstab.dart
  lib/views/pages/newsfeed/add_post.dart
  lib/views/pages/organization/accept_requests_page.dart
  lib/views/pages/organization/organization_members.dart
  lib/views/pages/organization/organization_settings.dart
  lib/views/pages/organization/switch_org_page.dart
  lib/views/pages/organization/update_organization.dart
  lib/views/pages/organization/update_profile_page.dart
  lib/views/widgets/about_tile.dart
  lib/views/widgets/alert_dialog_box.dart
  lib/views/widgets/common_divider.dart
  lib/views/widgets/custom_appbar.dart
  lib/views/widgets/internet_connectivity.dart
  lib/views/widgets/loading.dart
  lib/views/widgets/show_progress.dart
  lib/views/widgets/snackbar.dart
  lib/views/widgets/text_field_decoration.dart
Labels: discussion, good first issue

#811 App localization and language controller addition
  lang/en.json
  lang/es.json
  lang/fr.json
  lang/hi.json
  lang/zh-CN.json
  lib/controllers/lang_controller.dart
  lib/main.dart
  lib/services/app_localization.dart
  lib/views/pages/newsfeed/newsfeed.dart
  pubspec.yaml
Labels: GSoC

#787 script for automatically adding trailing commas
  .github/workflows/pull-request.yml
  .github/workflows/trailing_commas.py
  lib/controllers/org_controller.dart
  lib/controllers/post_controller.dart
  lib/services/queries_.dart
  lib/utils/api_functions.dart
  test/widget_tests/groups_page_test.dart
Labels: enhancement, github-externship, good first issue

#839 Updated CONTRIBUTING.md with new branching strategy
  CONTRIBUTING.md
Labels: documentation, enhancement

#863 [GSoC] - Code re-write and migration
  .github/workflows/pull-request.yml
  lib/constants/custom_theme.dart
  lib/enums/view_state.dart
  lib/generated_plugin_registrant.dart
  lib/locator.dart
  lib/main.dart
  lib/router.dart
  lib/services/navigation_service.dart
  lib/services/size_config.dart
  lib/splash_screen.dart
  lib/utils/validators.dart
  lib/viewModel/base_view_model.dart
  lib/views/after_auth_screens/feed_page/organization_feed.dart
  lib/views/home_page.dart
  lib/views/pre_auth_screens/change_password.dart
  lib/views/pre_auth_screens/login.dart
  lib/views/pre_auth_screens/recover.dart
  lib/views/pre_auth_screens/select_language.dart
  lib/views/pre_auth_screens/select_organization.dart
  lib/views/pre_auth_screens/set_url.dart
  lib/views/pre_auth_screens/signup_details.dart
  lib/views/pre_auth_screens/signup_holder.dart
  lib/views/pre_auth_screens/waiting_to_join_private_org.dart
  lib/widgets/join_org_tile.dart
  lib/widgets/pinned_carousel_widget.dart
  lib/widgets/post_detailed_page.dart
  lib/widgets/post_widget.dart
  lib/widgets/raised_round_edge_button.dart
  pubspec.yaml
Labels: GSoC
