Repository PalisadoesFoundation/talawa, pull requests merged in 2021-03, with the labels that each got.

#117 added the autofill option in the form and made the Docker container for the same and made the instruction.
  assets/images/docker_1.jpg
  assets/images/docker_2.jpg
  assets/images/docker_3.jpeg
  flutter_docker/.devcontainer/devcontainer.json
  flutter_docker/.dockerignore
  flutter_docker/Dockerfile
  flutter_docker/workspace/readme.md
  lib/generated_plugin_registrant.dart
  lib/views/pages/events/events.dart
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/widgets/about_tile.dart
Labels: enhancement, hold

#212 [SwitchOrganization] Snackbar optimization
  lib/views/pages/organization/profile_page.dart
Labels: bug, discussion

#273 Keyboard closing on direct clicking on set URL button
  lib/views/pages/login_signup/login_page.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/organization/create_organization.dart
Labels: bug

#328 Initial draft for PR Guidelines
  CONTRIBUTING.md
  PR-guidelines.md
  issue-guidelines.md
  templates/issue-template.md
  templates/pr-template.md
Labels: internal

#232 Solves Exception toast overflow on register form screen
  lib/views/pages/login_signup/register_form.dart
Labels: bug

#314 [Bug] - Profile Page Fix for currentOrgName null for any reason will so user …
  lib/views/pages/organization/profile_page.dart
Labels: bug

#350 [Feature] - Auto selected current organization on switch organization page
  lib/views/pages/organization/switch_org_page.dart
Labels: bug

#345 [ENHANCEMENT] Added the comments and removed unused variables
  lib/controllers/auth_controller.dart
  lib/controllers/org_controller.dart
  lib/generated_plugin_registrant.dart
  lib/locator.dart
  lib/main.dart
  lib/model/switch_org.dart
  lib/model/token.dart
  lib/model/user.dart
  lib/services/Queries.dart
  lib/services/preferences.dart
  lib/utils/apiFuctions.dart
  lib/view_models/base_model.dart
  lib/view_models/swtich_org_vm.dart
  lib/view_models/vm_login.dart
  lib/view_models/vm_register.dart
  lib/views/base_view.dart
  lib/views/pages/chat/chat.dart
  lib/views/pages/chat/groups.dart
  lib/views/pages/events/EventDetailPage.dart
  lib/views/pages/events/addEventPage.dart
  lib/views/pages/events/addTaskDialog.dart
  lib/views/pages/events/editEventDialog.dart
  lib/views/pages/events/events.dart
  lib/views/pages/events/registrantList.dart
  lib/views/pages/events/taskList.dart
  lib/views/pages/home_page.dart
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/login_signup/login_page.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/members/RegEventstab.dart
  lib/views/pages/members/memberDetails.dart
  lib/views/pages/members/members.dart
  lib/views/pages/members/userTaskstab.dart
  lib/views/pages/newsfeed/addPost.dart
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/newsfeed/newsfeed.dart
  lib/views/pages/organization/accept_requests_page.dart
  lib/views/pages/organization/create_organization.dart
  lib/views/pages/organization/join_organization.dart
  lib/views/pages/organization/organization_settings.dart
  lib/views/pages/organization/profile_page.dart
  lib/views/pages/organization/remove_member.dart
  lib/views/pages/organization/switch_org_page.dart
  lib/views/pages/organization/update_organization.dart
  lib/views/widgets/about_tile.dart
  lib/views/widgets/custom_appbar.dart
  lib/views/widgets/internet_connectivity.dart
  lib/views/widgets/snackbar.dart
  lib/views/widgets/success_toast.dart
Labels: good first issue

#373 Fixed the errors in register_form.dart file
  lib/views/pages/login_signup/register_form.dart
Labels: bug

#335 Non-existing url bug
  lib/views/pages/login_signup/login_page.dart
Labels: bug, enhancement

#348 Fixes Event Page format exception error
  lib/views/pages/events/events.dart
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/members/memberDetails.dart
Labels: bug

#283 resolved bug in regEvent
  lib/services/Queries.dart
  lib/views/pages/members/RegEventstab.dart
  lib/views/pages/members/userTaskstab.dart
Labels: bug, discussion

#360 Adding Validation on add post screen
  android/app/src/main/res/drawable/launch_background.xml
  lib/views/pages/newsfeed/addPost.dart
Labels: bug

#367 Fixes leave organisation button error
  lib/views/pages/organization/profile_page.dart
Labels: bug

#361 [BUG] Added functionality of like button and added comment button opens the comment
  lib/services/Queries.dart
  lib/views/pages/home_page.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/newsfeed/newsfeed.dart
Labels: bug, enhancement

#395 Fixed #363 Login page bugs
  lib/views/pages/login_signup/login_page.dart
Labels: bug

#403 Changed the TextInputAction to TextInputAction.next in Email Text field of Login form
  lib/views/pages/login_signup/login_form.dart
Labels: bug

#408 feat: added widget test for Login Page
  test/widget_tests/login_page_test.dart
Labels: good first issue, test

#394 Fixing broken link
  PR-guidelines.md
  issue-guidelines.md
Labels: documentation

#411 Created greetings for first time Issues and PRs
  .github/workflows/greetings.yml
  .github/workflows/issue.yml
Labels: internal

#378 [Fix] - Navigation fix after signup on creating new organization
  lib/views/pages/home_page.dart
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/login_signup/login_page.dart
  lib/views/pages/login_signup/register_form.dart
  lib/views/pages/organization/create_organization.dart
  lib/views/pages/organization/join_organization.dart
  lib/views/pages/organization/profile_page.dart
Labels: bug

#428 enables scrolling in comments
  lib/views/pages/newsfeed/newsArticle.dart
Labels: bug

#449 Fixed Bug #433 Memory Leak
  lib/views/pages/organization/join_organization.dart
Labels: bug, help wanted

#466 FIxed the re-loading and network image exception.
  lib/services/preferences.dart
  lib/utils/GQLClient.dart
  lib/views/pages/login_signup/set_url_page.dart
Labels: bug, good first issue

#405 Fixed Comment Button
  lib/services/Queries.dart
  lib/utils/apiFuctions.dart
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/newsfeed/newsfeed.dart
Labels: bug

#424 [Fix] - Organization setting related issues #355
  lib/services/Queries.dart
  lib/views/pages/organization/accept_requests_page.dart
  lib/views/pages/organization/organization_members.dart
  lib/views/pages/organization/organization_settings.dart
  lib/views/pages/organization/profile_page.dart
  lib/views/pages/organization/remove_member.dart
  lib/views/pages/organization/switch_org_page.dart
  lib/views/pages/organization/update_organization.dart
  lib/views/widgets/alert_dialog_box.dart
  lib/views/widgets/text_field_decoration.dart
  lib/views/widgets/toast_tile.dart
  pubspec.yaml
  test/widget_tests/organization_settings_test.dart
  test/widget_tests/profile_page_test.dart
Labels: bug, enhancement, help wanted, hold

#454 [BUG-FIX] Image Library Image Selection Fix
  lib/views/pages/login_signup/register_form.dart
Labels: bug

#464 [Fix] : Set Org URL page occurs in transitions between Register and Login screens
  lib/views/pages/login_signup/login_page.dart
  lib/views/pages/login_signup/register_page.dart
Labels: bug, good first issue, help wanted

#469 Updated validatePassword in validator.dart
  lib/utils/validator.dart
  test/validator_test.dart
Labels: good first issue

#471 Update register_form.dart
  lib/views/pages/login_signup/register_form.dart
  pubspec.yaml
Labels: good first issue

#437 [BUG] Resolve in comment section
  lib/views/pages/newsfeed/newsArticle.dart
  test/widget_tests/newsArticle_test.dart
Labels: bug, good first issue

#410 Fixed null values being displayed in Tasks Tab of User Info Screen.
  lib/services/Queries.dart
  lib/views/pages/members/userTaskstab.dart
  lib/views/pages/organization/switch_org_page.dart
  pubspec.yaml
  test/userTaskstab_test.dart
Labels: bug

#475 test: added more test cases
  test/widget_tests/set_url_page_test.dart
Labels: help wanted

#444 Member page will not stuck on loading if response is null (Not part of any organization)
  lib/views/pages/members/members.dart
  lib/views/pages/organization/accept_requests_page.dart
  test/widget_tests/member_page_test.dart
Labels: bug

#276 Filepicker replaced with imagepicker for registration
  lib/views/pages/login_signup/register_form.dart
Labels: bug, good first issue

#481 Toast Message fixes in Login Form and Registration Form
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/login_signup/register_form.dart
  pubspec.yaml
Labels: bug, good first issue

#486 Profile pic comments
  lib/views/pages/newsfeed/newsArticle.dart
Labels: bug, help wanted

#500 Email and password validator removed from login_form.dart
  lib/views/pages/login_signup/login_form.dart
Labels: bug, good first issue

#485 Event page bug
  lib/views/pages/events/events.dart
Labels: bug, good first issue, help wanted

#479 Adding Word limit to the input fields [Enhancement]
  lib/utils/validator.dart
  lib/views/pages/newsfeed/addPost.dart
  lib/views/pages/newsfeed/newsArticle.dart
  lib/views/pages/organization/create_organization.dart
Labels: bug, good first issue

#502 Adds Create event functionality and handles infinite loading bug
  lib/views/pages/events/addEventPage.dart
  lib/views/pages/events/events.dart
Labels: bug, help wanted

#511 test: added tests for Register Page & refactored folder
  test/helper.dart
  test/unit_tests/userTaskstab_test.dart
  test/unit_tests/validator_test.dart
  test/widget_tests/member_page_test.dart
  test/widget_tests/newsArticle_test.dart
  test/widget_tests/register_form_test.dart
  test/widget_tests/set_url_page_test.dart
Labels: help wanted

#456 Infinite loading issue fixed on all screens.
  assets/images/error.svg
  lib/views/pages/events/events.dart
  lib/views/pages/members/members.dart
  lib/views/pages/newsfeed/newsfeed.dart
  lib/views/pages/organization/join_organization.dart
  lib/views/pages/organization/profile_page.dart
  lib/views/widgets/loading.dart
  pubspec.yaml
  test/widget_tests/profile_page_test.dart
Labels: bug

#420 change about icon and update profile icon to appropriate icon
  lib/views/pages/organization/profile_page.dart
  lib/views/widgets/about_tile.dart
Labels: enhancement, good first issue, hold

#418 Added Spinner to Join Button
  lib/views/pages/organization/join_organization.dart
Labels: enhancement, hold

#527 fix: behaviour of validators in register and home page
  lib/utils/validator.dart
  lib/views/pages/login_signup/login_form.dart
  lib/views/pages/login_signup/register_form.dart
  test/unit_tests/validator_test.dart
Labels: bug

#534 New logo added as app Icon.
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/images/talawaLogo-dark.png
  assets/images/talawaLogo-noBg.png
  assets/images/talawaLogo.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/utils/uidata.dart
  pubspec.yaml
Labels: good first issue

#546 Bugfix/fix comment icon
  lib/views/pages/newsfeed/newsArticle.dart
  test/widget_tests/newsArticle_test.dart
Labels: bug, good first issue

#550 [bug-fix]Rewritten the wrong like-dislike logic ⚙
  lib/views/pages/newsfeed/newsfeed.dart
Labels: bug, help wanted

#446 [FIX] Issue174 Update Profile Page Screen
  lib/services/Queries.dart
  lib/views/pages/organization/profile_page.dart
  lib/views/pages/organization/update_profile_page.dart
  test/updateProfile_test.dart
  test/widget_tests/profile_page_test.dart
  test/widget_tests/updateProfileWidget_test.dart
Labels: bug, help wanted

#530 Fixed the Alphabet Transparent header issue.(Bugfix)
  lib/views/pages/members/members.dart
Labels: bug

#552 [BugFix] Event Scrolling Screen Fix
  lib/views/pages/events/events.dart
Labels: bug
