Repository PalisadoesFoundation/talawa, pull requests merged in 2021-08, with the labels that each got.

#951 `Bug Fix` Waiting page join org button bug fix
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lang/en.json
  lang/es.json
  lang/fr.json
  lang/hi.json
  lang/zh.json
  lib/services/database_mutation_functions.dart
  lib/utils/app_localization.dart
  lib/view_model/pre_auth_view_models/select_organization_view_model.dart
  lib/view_model/pre_auth_view_models/waiting_view_model.dart
  lib/views/pre_auth_screens/waiting_to_join_private_org.dart
  lib/widgets/rich_text.dart
Labels: bug, GSoC

#947 `Feature` Donation UI and functionality(with static payment keys)
  .github/workflows/pull-request.yml
  .github/workflows/push.yaml
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/values-night/styles.xml
  android/app/src/profile/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  ios/Runner/Base.lproj/Main.storyboard
  lib/constants/constants.dart
  lib/generated_plugin_registrant.dart
  lib/services/navigation_service.dart
  lib/view_model/after_auth_view_models/profile_view_models/profile_page_view_model.dart
  lib/views/after_auth_screens/profile/profile_page.dart
  pubspec.yaml
Labels: GSoC, desired feature

#956 `Feature` AppTour for new users.
  .flutter-plugins-dependencies
  .github/workflows/pull-request.yml
  .github/workflows/push.yaml
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/demo_server_data/pinned_post_demo_data.dart
  lib/router.dart
  lib/splash_screen.dart
  lib/view_model/after_auth_view_models/feed_view_models/organization_feed_view_model.dart
  lib/view_model/after_auth_view_models/profile_view_models/profile_page_view_model.dart
  lib/view_model/main_screen_view_model.dart
  lib/view_model/pre_auth_view_models/login_view_model.dart
  lib/view_model/pre_auth_view_models/signup_details_view_model.dart
  lib/view_model/widgets_view_models/custom_drawer_view_model.dart
  lib/views/after_auth_screens/events/explore_events.dart
  lib/views/after_auth_screens/feed/organization_feed.dart
  lib/views/after_auth_screens/profile/profile_page.dart
  lib/views/main_screen.dart
  lib/widgets/custom_alert_dialog.dart
  lib/widgets/custom_drawer.dart
  lib/widgets/post_list_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: GSoC, desired feature

#960 [Bug Fix] Signup screen progress popup fix
  lib/view_model/pre_auth_view_models/signup_details_view_model.dart
Labels: bug

#967 [GSoC] Language query
  lib/utils/queries.dart
  lib/view_model/lang_view_model.dart
Labels: GSoC
